version: "3"

services:
  fake-log-generator:
    image: alpine:latest
    container_name: alpine
    volumes:
      - ./nginx/fake-log-generator.sh:/fake-log-generator.sh
      - ./logs:/var/log/
    command: ["/bin/sh", "-c", "apk update && apk add bash && bash /fake-log-generator.sh"]
  # nginx:
  #   container_name: nginx
  #   image: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./logs:/var/log/nginx 
  #   restart: always
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  loki:
    image: grafana/loki:2.6.1
    container_name: loki
    # volumes:
    #   - ./loki/:/etc/loki/
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - 3100:3100
    depends_on:
      - promtail
  promtail:
    image: grafana/promtail:2.6.1
    container_name: promtail
    volumes:
      - ./logs/:/var/log/nginx 
      - ./promtail:/etc/promtail/
    command: -config.file=/etc/promtail/promtail.yml
    depends_on:
      - fake-log-generator
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    depends_on:
      - loki